from abc import ABC
from collections.abc import Sequence

from selenium.webdriver import Chrome as SeChrome
from selenium.webdriver.remote.shadowroot import ShadowRoot
from seleniumwire.webdriver import Chrome

type Driver = Chrome | SeChrome  # pyright: ignore[reportGeneralTypeIssues]

class BaseWebElement(ABC): ...

class WebElement(BaseWebElement):
    def __init__(self, parent: Driver, id_: str) -> None: ...
    @property
    def session_id(self) -> str: ...
    @property
    def tag_name(self) -> str: ...
    @property
    def text(self) -> str: ...
    def click(self) -> None: ...
    def submit(self) -> None: ...
    def clear(self) -> None: ...
    def get_property(
        self,
        name: str,
    ) -> str | bool | WebElement | dict: ...
    def get_dom_attribute(self, name: str) -> str: ...
    def get_attribute(self, name: str) -> str | None: ...
    def is_selected(self) -> bool: ...
    def send_keys(self, *value: str) -> None: ...
    @property
    def shadow_root(self) -> ShadowRoot: ...

    # RenderedWebElement Items
    def is_displayed(self) -> bool: ...
    @property
    def location_once_scrolled_into_view(self) -> dict: ...
    @property
    def size(self) -> dict: ...
    def value_of_css_property(self, property_name: str) -> str: ...
    @property
    def location(self) -> dict: ...
    @property
    def rect(self) -> dict: ...
    @property
    def aria_role(self) -> str: ...
    @property
    def accessible_name(self) -> str: ...
    @property
    def screenshot_as_base64(self) -> str: ...
    @property
    def screenshot_as_png(self) -> bytes: ...
    def screenshot(self, filename: str) -> bool: ...
    @property
    def parent(self) -> Driver: ...
    @property
    def id(self) -> str: ...
    def __eq__(self, element: WebElement) -> bool: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def __ne__(self, element: WebElement) -> bool: ...  # pyright: ignore[reportIncompatibleMethodOverride]

    # Private Methods
    def _execute(self, command: str, params=None): ...  # noqa: ANN001, ANN202
    def find_element(
        self,
        by: str = ...,
        value: str | None = None,
    ) -> WebElement: ...
    def find_elements(
        self,
        by: str = ...,
        value: str | None = None,
    ) -> Sequence[WebElement]: ...
    def __hash__(self) -> int: ...
    def _upload(self, filename: str) -> None: ...
